site_name: Kamaji Documentation
site_url: https://jcorbin406.github.io/Kamaji/
repo_url: https://github.com/JCorbin406/kamaji
site_description: "Documentation for the Kamaji multi-agent simulation environment."
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: started/installation.md
    - Quickstart: started/quickstart.md
    - Examples: started/examples.md
  - Concepts:
    - Configuration: concepts/configuration.md
    - Agents: concepts/agents.md
    - Simulator: concepts/simulator.md
    - Controls: concepts/controls.md
    - Dynamics: concepts/dynamics.md
    - Environment: concepts/environment.md
  - Methods: methods.md
  - Examples:
    - CBF: examples/CBF.md
    - Auction: examples/auction.md
    - Sequential: examples/sequential.md
  - About: about.md
  - License: license.md
  - API Reference:
      - Overview: api.md
      - Agent: api/agent.md
      - Simulator: api/simulator.md
      - Auction: api/auction.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.emoji

extra_javascript:
  - js/mathjax_config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Same as Ardupilot/ROS documentation.
theme:
  name: readthedocs
  logo: img/KamajiLogo.png
  include_homepage_in_sidebar: False
  collapse_navigation: False
  titles_only: False
  sticky_navigation: True
